const products = [
    { id: 1, name: 'Laptop', price: 1200, image: 'https://picsum.photos/360', category: 'electronics', qtyAvailable: 20, qtySelected: 0 },
    { id: 2, name: 'Smartphone', price: 800, image: 'https://picsum.photos/370', category: 'electronics', qtyAvailable: 20, qtySelected: 0 },
    { id: 3, name: 'Headphones', price: 150, image: 'https://picsum.photos/380', category: 'electronics', qtyAvailable: 20, qtySelected: 0 },
    { id: 4, name: 'Smartwatch', price: 250, image: 'https://picsum.photos/390', category: 'electronics', qtyAvailable: 20, qtySelected: 0 },
    { id: 5, name: 'Bluetooth Speaker', price: 100, image: 'https://picsum.photos/400', category: 'electronics', qtyAvailable: 20, qtySelected: 0 },
    { id: 6, name: 'T-Shirt', price: 25, image: 'https://picsum.photos/410', category: 'clothing', qtyAvailable: 20, qtySelected: 0 },
    { id: 7, name: 'Jeans', price: 50, image: 'https://picsum.photos/420', category: 'clothing', qtyAvailable: 20, qtySelected: 0 },
    { id: 8, name: 'Jacket', price: 90, image: 'https://picsum.photos/430', category: 'clothing', qtyAvailable: 20, qtySelected: 0 },
    { id: 9, name: 'Sneakers', price: 120, image: 'https://picsum.photos/440', category: 'clothing', qtyAvailable: 20, qtySelected: 0 },
    { id: 10, name: 'Hat', price: 20, image: 'https://picsum.photos/450', category: 'clothing', qtyAvailable: 20, qtySelected: 0 },
    { id: 11, name: 'Pizza', price: 15, image: 'https://picsum.photos/460', category: 'food', qtyAvailable: 20, qtySelected: 0 },
    { id: 12, name: 'Burger', price: 10, image: 'https://picsum.photos/470', category: 'food', qtyAvailable: 20, qtySelected: 0 },
    { id: 13, name: 'Pasta', price: 12, image: 'https://picsum.photos/480', category: 'food', qtyAvailable: 20, qtySelected: 0 },
    { id: 14, name: 'Salad', price: 8, image: 'https://picsum.photos/490', category: 'food', qtyAvailable: 20, qtySelected: 0 },
    { id: 15, name: 'Sandwich', price: 7, image: 'https://picsum.photos/500', category: 'food', qtyAvailable: 20, qtySelected: 0 },
    { id: 16, name: 'Blender', price: 70, image: 'https://picsum.photos/510', category: 'home and kitchen', qtyAvailable: 20, qtySelected: 0 },
    { id: 17, name: 'Microwave', price: 150, image: 'https://picsum.photos/520', category: 'home and kitchen', qtyAvailable: 20, qtySelected: 0 },
    { id: 18, name: 'Toaster', price: 40, image: 'https://picsum.photos/530', category: 'home and kitchen', qtyAvailable: 20, qtySelected: 0 },
    { id: 19, name: 'Coffee Maker', price: 100, image: 'https://picsum.photos/540', category: 'home and kitchen', qtyAvailable: 20, qtySelected: 0 },
    { id: 20, name: 'Air Fryer', price: 130, image: 'https://picsum.photos/550', category: 'home and kitchen', qtyAvailable: 20, qtySelected: 0 },
    { id: 21, name: 'Milk', price: 4, image: 'https://picsum.photos/560', category: 'grocery', qtyAvailable: 20, qtySelected: 0 },
    { id: 22, name: 'Bread', price: 3, image: 'https://picsum.photos/570', category: 'grocery', qtyAvailable: 20, qtySelected: 0 },
    { id: 23, name: 'Eggs', price: 6, image: 'https://picsum.photos/580', category: 'grocery', qtyAvailable: 20, qtySelected: 0 },
    { id: 24, name: 'Cheese', price: 8, image: 'https://picsum.photos/590', category: 'grocery', qtyAvailable: 20, qtySelected: 0 },
    { id: 25, name: 'Butter', price: 5, image: 'https://picsum.photos/600', category: 'grocery', qtyAvailable: 20, qtySelected: 0 },
];

export default products;
